object frmEtiquetasNomePrat: TfrmEtiquetasNomePrat
  Left = 24
  Top = 89
  BorderIcons = []
  BorderStyle = bsSingle
  Caption = 'Etiquetas Balc'#227'o'
  ClientHeight = 476
  ClientWidth = 751
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
  object Bevel1: TBevel
    Left = 370
    Top = 3
    Width = 3
    Height = 466
  end
  object btSair: TBmsXPButton
    Left = 656
    Top = 441
    Width = 80
    Height = 21
    Caption = '&Sair'
    Layout = tlTop
    WordWrap = False
    ShowAccelChar = True
    TabOrder = 30
    OnClick = btSairClick
  end
  object btVisualizar: TBmsXPButton
    Left = 560
    Top = 441
    Width = 80
    Height = 21
    Caption = '&Visualizar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    Layout = tlTop
    WordWrap = False
    ShowAccelChar = True
    ParentFont = False
    TabOrder = 31
    OnClick = btVisualizarClick
  end
  object lbl_edtNome1: TLabeledEdit
    Left = 4
    Top = 26
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 54
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o1'
    MaxLength = 40
    TabOrder = 0
  end
  object lbl_edtVlr1: TLabeledEdit
    Left = 288
    Top = 26
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 30
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor1'
    MaxLength = 6
    TabOrder = 2
  end
  object lbl_edtCompl1: TLabeledEdit
    Left = 178
    Top = 26
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 70
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento1'
    MaxLength = 21
    TabOrder = 1
  end
  object lbl_edtNome2: TLabeledEdit
    Left = 5
    Top = 66
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 54
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o2'
    MaxLength = 40
    TabOrder = 3
  end
  object lbl_edtCompl2: TLabeledEdit
    Left = 178
    Top = 66
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 70
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento2'
    MaxLength = 21
    TabOrder = 4
  end
  object lbl_edtVlr2: TLabeledEdit
    Left = 288
    Top = 66
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 30
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor2'
    MaxLength = 6
    TabOrder = 5
  end
  object lbl_edtNome3: TLabeledEdit
    Left = 5
    Top = 109
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 54
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o3'
    MaxLength = 40
    TabOrder = 6
  end
  object lbl_edtCompl3: TLabeledEdit
    Left = 178
    Top = 109
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 70
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento3'
    MaxLength = 21
    TabOrder = 7
  end
  object lbl_edtVlr3: TLabeledEdit
    Left = 288
    Top = 109
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 30
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor3'
    MaxLength = 6
    TabOrder = 8
  end
  object lbl_edtNome4: TLabeledEdit
    Left = 5
    Top = 155
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 54
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o4'
    MaxLength = 40
    TabOrder = 9
  end
  object lbl_edtCompl4: TLabeledEdit
    Left = 178
    Top = 155
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 70
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento4'
    MaxLength = 21
    TabOrder = 10
  end
  object lbl_edtVlr4: TLabeledEdit
    Left = 288
    Top = 155
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 30
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor4'
    MaxLength = 6
    TabOrder = 11
  end
  object lbl_edtNome5: TLabeledEdit
    Left = 6
    Top = 198
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 54
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o5'
    MaxLength = 40
    TabOrder = 12
  end
  object lbl_edtCompl5: TLabeledEdit
    Left = 179
    Top = 198
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 70
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento5'
    MaxLength = 21
    TabOrder = 13
  end
  object lbl_edtVlr5: TLabeledEdit
    Left = 289
    Top = 198
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 30
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor5'
    MaxLength = 6
    TabOrder = 14
  end
  object lbl_edtNome6: TLabeledEdit
    Left = 6
    Top = 241
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 54
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o6'
    MaxLength = 40
    TabOrder = 15
  end
  object lbl_edtCompl6: TLabeledEdit
    Left = 179
    Top = 241
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 70
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento6'
    MaxLength = 21
    TabOrder = 16
  end
  object lbl_edtVlr6: TLabeledEdit
    Left = 289
    Top = 241
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 30
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor6'
    MaxLength = 6
    TabOrder = 17
  end
  object lbl_edtNome7: TLabeledEdit
    Left = 7
    Top = 283
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 54
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o7'
    MaxLength = 40
    TabOrder = 18
  end
  object lbl_edtCompl7: TLabeledEdit
    Left = 180
    Top = 283
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 70
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento7'
    MaxLength = 21
    TabOrder = 19
  end
  object lbl_edtVlr7: TLabeledEdit
    Left = 290
    Top = 283
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 30
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor7'
    MaxLength = 6
    TabOrder = 20
  end
  object lbl_edtNome8: TLabeledEdit
    Left = 7
    Top = 326
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 54
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o8'
    MaxLength = 40
    TabOrder = 21
  end
  object lbl_edtCompl8: TLabeledEdit
    Left = 180
    Top = 326
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 70
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento8'
    MaxLength = 21
    TabOrder = 22
  end
  object lbl_edtVlr8: TLabeledEdit
    Left = 290
    Top = 326
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 30
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor8'
    MaxLength = 6
    TabOrder = 23
  end
  object lbl_edtNome9: TLabeledEdit
    Left = 7
    Top = 369
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 54
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o9'
    MaxLength = 40
    TabOrder = 24
  end
  object lbl_edtCompl9: TLabeledEdit
    Left = 180
    Top = 369
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 70
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento9'
    MaxLength = 21
    TabOrder = 25
  end
  object lbl_edtVlr9: TLabeledEdit
    Left = 290
    Top = 369
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 30
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor9'
    MaxLength = 6
    TabOrder = 26
  end
  object lbl_edtNome10: TLabeledEdit
    Left = 7
    Top = 409
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o10'
    MaxLength = 40
    TabOrder = 27
  end
  object lbl_edtCompl10: TLabeledEdit
    Left = 180
    Top = 409
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento10'
    MaxLength = 21
    TabOrder = 28
  end
  object lbl_edtVlr10: TLabeledEdit
    Left = 290
    Top = 409
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor10'
    MaxLength = 6
    TabOrder = 29
  end
  object BmsXPButton1: TBmsXPButton
    Left = 200
    Top = 440
    Width = 80
    Height = 21
    Caption = '&Limpar'
    Layout = tlTop
    WordWrap = False
    ShowAccelChar = True
    TabOrder = 32
    OnClick = BmsXPButton1Click
  end
  object lbl_edtNome11: TLabeledEdit
    Left = 377
    Top = 26
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o11'
    MaxLength = 40
    TabOrder = 33
  end
  object lbl_edtNome12: TLabeledEdit
    Left = 378
    Top = 66
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o12'
    MaxLength = 40
    TabOrder = 34
  end
  object lbl_edtNome13: TLabeledEdit
    Left = 378
    Top = 109
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o13'
    MaxLength = 40
    TabOrder = 35
  end
  object lbl_edtNome14: TLabeledEdit
    Left = 378
    Top = 155
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o14'
    MaxLength = 40
    TabOrder = 36
  end
  object lbl_edtNome15: TLabeledEdit
    Left = 379
    Top = 198
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o15'
    MaxLength = 40
    TabOrder = 37
  end
  object lbl_edtNome16: TLabeledEdit
    Left = 379
    Top = 241
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o16'
    MaxLength = 40
    TabOrder = 38
  end
  object lbl_edtNome17: TLabeledEdit
    Left = 380
    Top = 283
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o17'
    MaxLength = 40
    TabOrder = 39
  end
  object lbl_edtNome18: TLabeledEdit
    Left = 380
    Top = 326
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o18'
    MaxLength = 40
    TabOrder = 40
  end
  object lbl_edtNome19: TLabeledEdit
    Left = 380
    Top = 369
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o19'
    MaxLength = 40
    TabOrder = 41
  end
  object lbl_edtNome20: TLabeledEdit
    Left = 380
    Top = 409
    Width = 169
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 60
    EditLabel.Height = 13
    EditLabel.Caption = 'Descri'#231#227'o20'
    MaxLength = 40
    TabOrder = 42
  end
  object lbl_edtCompl11: TLabeledEdit
    Left = 551
    Top = 26
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento11'
    MaxLength = 21
    TabOrder = 43
  end
  object lbl_edtCompl12: TLabeledEdit
    Left = 551
    Top = 66
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento12'
    MaxLength = 21
    TabOrder = 44
  end
  object lbl_edtCompl13: TLabeledEdit
    Left = 551
    Top = 109
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento13'
    MaxLength = 21
    TabOrder = 45
  end
  object lbl_edtCompl14: TLabeledEdit
    Left = 551
    Top = 155
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento14'
    MaxLength = 21
    TabOrder = 46
  end
  object lbl_edtCompl15: TLabeledEdit
    Left = 552
    Top = 198
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento15'
    MaxLength = 21
    TabOrder = 47
  end
  object lbl_edtCompl16: TLabeledEdit
    Left = 552
    Top = 241
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento16'
    MaxLength = 21
    TabOrder = 48
  end
  object lbl_edtCompl17: TLabeledEdit
    Left = 553
    Top = 283
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento17'
    MaxLength = 21
    TabOrder = 49
  end
  object lbl_edtCompl18: TLabeledEdit
    Left = 553
    Top = 326
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento18'
    MaxLength = 21
    TabOrder = 50
  end
  object lbl_edtCompl19: TLabeledEdit
    Left = 553
    Top = 369
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento19'
    MaxLength = 21
    TabOrder = 51
  end
  object lbl_edtCompl20: TLabeledEdit
    Left = 553
    Top = 409
    Width = 105
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 76
    EditLabel.Height = 13
    EditLabel.Caption = 'Complemento20'
    MaxLength = 21
    TabOrder = 52
  end
  object lbl_edtVlr11: TLabeledEdit
    Left = 662
    Top = 26
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor11'
    MaxLength = 6
    TabOrder = 53
  end
  object lbl_edtVlr12: TLabeledEdit
    Left = 662
    Top = 66
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor12'
    MaxLength = 6
    TabOrder = 54
  end
  object lbl_edtVlr13: TLabeledEdit
    Left = 662
    Top = 109
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor13'
    MaxLength = 6
    TabOrder = 55
  end
  object lbl_edtVlr14: TLabeledEdit
    Left = 662
    Top = 155
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor14'
    MaxLength = 6
    TabOrder = 56
  end
  object lbl_edtVlr15: TLabeledEdit
    Left = 663
    Top = 198
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor15'
    MaxLength = 6
    TabOrder = 57
  end
  object lbl_edtVlr16: TLabeledEdit
    Left = 663
    Top = 241
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor16'
    MaxLength = 6
    TabOrder = 58
  end
  object lbl_edtVlr17: TLabeledEdit
    Left = 664
    Top = 283
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor17'
    MaxLength = 6
    TabOrder = 59
  end
  object lbl_edtVlr18: TLabeledEdit
    Left = 664
    Top = 326
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor18'
    MaxLength = 6
    TabOrder = 60
  end
  object lbl_edtVlr19: TLabeledEdit
    Left = 664
    Top = 369
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor19'
    MaxLength = 6
    TabOrder = 61
  end
  object lbl_edtVlr20: TLabeledEdit
    Left = 664
    Top = 409
    Width = 71
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 36
    EditLabel.Height = 13
    EditLabel.Caption = 'Valor20'
    MaxLength = 6
    TabOrder = 62
  end
end
